<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/user.proto

namespace GPBMetadata\Grpc;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
´
grpc/user.protouser"
IdReq

id ("I
UserInfoReply

id (
name (	
number (	
gender (	23
user+
getUser.user.IdReq.user.UserInfoReplybproto3'
        , true);

        static::$is_initialized = true;
    }
}

